version: "3.9"

networks:
  lan: {}

volumes:
  mongo: {}
  mysql: {}

services:

  server-proxy:
    container_name: ${SERVICE_NAME:-example}-${SERVER_PROXY_HOST}
    image: nginx
    hostname: ${SERVER_PROXY_HOST}
    networks:
      - lan
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/server-proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db-mongo
      - db-mysql
      - api-server

  db-mongo:
    container_name: ${SERVICE_NAME:-example}-${DB_MONGO_HOST}
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_MONGO_ROOT_PASS}
      MONGO_INITDB_DATABASE: ${DB_MONGO_NAME}
      MONGO_INITDB_USER: ${DB_MONGO_USER}
      MONGO_INITDB_PWD: ${DB_MONGO_PASS}
    hostname: ${DB_MONGO_HOST}
    networks:
      - lan
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
      - ./docker/db-mongo/init:/docker-entrypoint-initdb.d

  db-mysql:
    container_name: ${SERVICE_NAME:-example}-${DB_MYSQL_HOST}
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_ROOT_PASS}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASS}
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
    command: --default-authentication-plugin=mysql_native_password
    hostname: ${DB_MYSQL_HOST}
    networks:
      - lan
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/db-mysql/init:/docker-entrypoint-initdb.d

  api-server:
    container_name: ${SERVICE_NAME:-example}-${SERVER_API_HOST}
    image: ${SERVICE_NAME:-example}-${SERVER_API_HOST}:latest
    build:
      context: ./
      dockerfile: ./docker/server-api/Dockerfile
    environment:
      SERVER_API_HOST : ${SERVER_API_HOST}
      SERVER_API_PORT : ${SERVER_API_PORT}
      NODE_ENV   : ${NODE_ENV:-dev}
      
      MONGO_HOST : ${MONGO_HOST}
      MONGO_PORT : ${MONGO_PORT}
      MONGO_NAME : ${MONGO_NAME}
      MONGO_USER : ${MONGO_USER}
      MONGO_PASS : ${MONGO_PASS}

      MYSQL_HOST : ${MYSQL_HOST}
      MYSQL_PORT : ${MYSQL_PORT}
      MYSQL_NAME : ${MYSQL_NAME}
      MYSQL_USER : ${MYSQL_USER}
      MYSQL_PASS : ${MYSQL_PASS}
    working_dir: /app
    command: npm run develop
    hostname: ${SERVER_API_HOST}
    networks:
      - lan
    ports:
      - 3000:3000 
      - 9229:9229 # node debugging port
    volumes:
      - ./:/app
    depends_on:
      - db-mongo